-- Add photo crop parameters to people table
ALTER TABLE people
ADD COLUMN IF NOT EXISTS crop_x FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS crop_y FLOAT DEFAULT 0,
ADD COLUMN IF NOT EXISTS crop_width FLOAT DEFAULT 100,
ADD COLUMN IF NOT EXISTS crop_height FLOAT DEFAULT 100,
ADD COLUMN IF NOT EXISTS zoom FLOAT DEFAULT 1;
